[package]
name = "tenex"
version = "0.1.0"
edition = "2018"

[features]
default = []
full = ["ipapi", "nws", "email"]
ipapi = ["net", "obj"]
nws = ["net", "obj"]
email = ["lettre", "net"]
[dependencies]
# rlib
ctx = { version = "0.1.0", path = "../rlib/ctx" }
cfg = { version = "0.1.0", path = "../rlib/cfg" }
net = { version = "0.1.0", path = "../rlib/net", features = ["client"], optional = true }
obj = { version = "0.1.0", path = "../rlib/obj", optional = true }
logger = { version = "0.1.0", path = "../rlib/logger" }
# contrib
serde_json = "1.0.66"
serde = { version = "1.0.127", features = ["derive"] }
ron = "0.6.4"
chrono = { version = "0.4.19", features = ["serde"] }
lettre = { version = "0.10.0-rc.3", path = "../contrib/rust/lettre", features = ["smtp-transport", "tokio1", "tokio1-rustls-tls", "builder"], optional = true }