[package]
name = "google"
version = "0.1.0"
edition = "2021"
[dependencies]
common = { path = "common" }
anyhow = "~1.0"
serde = "~1.0"
tokio = { version = "1.13", features = ["fs"] }
hyper = "0.14.14"
hyper-rustls = "0.22.1"
